name: Blaze4j Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  benchmark:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [22]  # Test only with Java 22

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          
      - name: Build with Maven
        run: |
          ls -la
          pwd
          if [ -d "spring-boot-example" ]; then
            cd spring-boot-example
            mvn clean package
          else
            # Try to find where the code is
            find . -type d -maxdepth 2
            # If we're already in the spring-boot-example directory
            if [ -f "pom.xml" ]; then
              mvn clean package
            else
              echo "Cannot find spring-boot-example directory or pom.xml"
              exit 1
            fi
          fi
        
      - name: Start Spring Boot app
        run: |
          # Determine if we're in the spring-boot-example directory or need to cd into it
          if [ -d "spring-boot-example" ]; then
            cd spring-boot-example
          fi
          
          # Check if we're in the right directory
          if [ ! -f "pom.xml" ]; then
            echo "Cannot find pom.xml - wrong directory"
            pwd
            ls -la
            exit 1
          fi
          
          # Start the Spring Boot app
          echo "Starting Spring Boot app..."
          nohup mvn spring-boot:run -Dspring-boot.run.jvmArguments="--enable-native-access=ALL-UNNAMED" > app.log 2>&1 &
          
          # Wait for app to start
          if [ "$RUNNER_OS" == "Windows" ]; then
            sleep 30
          else
            sleep 15
          fi
          
          # Check if the app started successfully
          if ! curl -s http://localhost:8080/actuator/health &>/dev/null; then
            echo "Spring Boot app failed to start. Here's the log:"
            cat app.log
            exit 1
          else
            echo "Spring Boot app started successfully"
          fi
        shell: bash
      
      # Generate sample data files for testing
      - name: Generate sample data
        run: |
          # Determine if we're in the spring-boot-example directory or need to cd into it
          if [ -d "spring-boot-example" ]; then
            cd spring-boot-example
          fi
          
          # Check if we're in the right directory
          if [ ! -f "pom.xml" ]; then
            echo "Cannot find pom.xml - wrong directory"
            pwd
            ls -la
            exit 1
          fi
          
          # Create directories
          mkdir -p src/main/resources/example
          
          # Create small sample file
          echo '[{"id":"EMP00001","fullName":"Test Employee","birthDate":"1990-01-01","department":"HR","title":"Manager","salary":50000,"currency":"USD","address":{"street":"123 Main St","city":"Testville","postalCode":"12345","country":"US"},"contacts":[{"type":"email","value":"test@example.com","primary":true}]}]' > employees-sample.json
          
          # Show what we've created
          ls -la
          ls -la src/main/resources/example
          
          # Compile and run the data generator to create a small pre-generated file
          echo "Generating sample data file..."
          mvn compile exec:java -Dexec.mainClass="com.example.util.DataGenerator" -Dexec.args="1000" -q > src/main/resources/example/employees-large.json
          
          # Verify file was created
          if [ -f "src/main/resources/example/employees-large.json" ]; then
            echo "Sample data file created successfully"
            ls -la src/main/resources/example
          else
            echo "Failed to create sample data file"
            exit 1
          fi
          
      - name: Run benchmarks
        run: |
          # Determine if we're in the spring-boot-example directory or need to cd into it
          if [ -d "spring-boot-example" ]; then
            cd spring-boot-example
          fi
          
          # Check if app is running
          if ! curl -s http://localhost:8080 &>/dev/null; then
            echo "Spring Boot app is not running. Here's the log:"
            cat app.log
            exit 1
          fi
          
          echo "=== Small sample benchmark ==="
          curl -v -F "file=@employees-sample.json" http://localhost:8080/api/upload
          
          echo -e "\n=== 10k records benchmark (5 runs) ==="
          for i in {1..5}; do
            curl -s http://localhost:8080/api/benchmark
            echo
          done
          
          echo -e "\n=== 100k records benchmark ==="
          curl "http://localhost:8080/api/benchmark?size=100000"
        shell: bash
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-java${{ matrix.java }}
          path: spring-boot-example/app.log
